### ISSUE TITLE
clusteradm join error

### ISSUE THREAD

**Issue by wangzd1** [open-cluster-management-io/clusteradm#106]
I try to use "clusteradm join" command to join a managed cluster into a hub cluster,but got this error
Error: "join/klusterlets.crd.yaml" (string): the server could not find the requested resource

managed cluster info:
kubernetes: v1.14
installed klusterlet

**Comment by xauthulei** [comment]
Could I know what is your `clusteradm` version ?Thanks

**Comment by wangzd1** [comment]
clusteradm version:v0.1.0-alpha.7

**Comment by wangzd1** [comment]
It is incompatible between 1.14  and 1.16+ in the apiVersion of crd，i will try to downgrade the kluster crd's apiVersion.Thanks
