### ISSUE TITLE
command to create a sample app

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/clusteradm#108]
In order to ease the barrier of entry for deploying applications across multicluster using OCM, create a new clusteradm subcommand that generates a sample application that can be deployed into multiple managed clusters. This inspiration comes from the `helm create` command: https://helm.sh/docs/helm/helm_create

I suggest we starts with something easy: `clusteradm create app sample-app`
This will create a folder `sample-app` containing yaml files that upon kubectl apply will perform a helm repo nginx app deployment to all the managed clusters.

What do you think @itdove ?

/assign mikeshng

**Comment by itdove** [comment]
Hi @mikeshng 
Wonder if we should not take a example from https://kubernetes.io/docs/tutorials/ but it is up to you.
I also wonder if the sample-app not be part of the -h , I don't know how much a `app` can be templated but for me a sample should be part of the documentation or located in a repo, with a repo the user could do:
`clusteradm install app <my_app_name> --repo-url <location of the repo> --values <custom_value>`
The `repo-url` could be a github, ftp, files.... to basically the clusteradm template which are currently in the clusteradm binary will be in this case in an external repo.
So I would add that sample in a shared repo that end-user can look at and use it.

**Comment by mikeshng** [comment]
Based on discussion with @itdove 

`clusteradm create app --sample` will install the sample app that is a Helm ngix deployment to all managed clusters.
`clusteradm create app --sample --dry-run --output-file /path/to/files` will generate the yamls.

in the future, not to be contained in this issue, other full blown param options that are not sample related.
`clusteradm create app --repo-type <type of repo> --repo-url <location of the repo> --clusters <list of clusters>`
