### ISSUE TITLE
"Error: the registration agent is not ready yet, please check it manually" when joining a cluster

### ISSUE THREAD

**Issue by pdettori** [open-cluster-management-io/clusteradm#109]
Following the quick start in https://open-cluster-management.io/getting-started/quick-start/ , when I run the `clusteradm join` command, the command stays stuck in "Waiting for the management components to become ready..." and then it times out.

```
Waiting for the management components to become ready...
Error: the registration agent is not ready yet, please check it manually
```

It looks like it's waiting for all components installed by Klusterlet to be available, however some components are only started after the `clusteredm accept` command is ran on the hub, and in that scenario then all components become available.

**Comment by mikeshng** [comment]
Thank you for reporting this. Maybe there is a recent change that broke the behaviour of join command. I will try to reproduce.

**Comment by mikeshng** [comment]
I just noticed we haven't release a clusteradm version in a while and it might no longer compatible with the latest klusterlet? 

@pdettori which version of clusteradm are you using? We are releasing OCM v0.6.0 soon and we will do a first non-alpha release of clusteradm.

**Comment by pdettori** [comment]
@mikeshng this is the version I am using:
```
$ clusteradm version
client		version	:0.1.0-alpha.7
server release	version	:v1.21.1
```

**Comment by mikeshng** [comment]
@pdettori can you try the latest release? https://github.com/open-cluster-management-io/clusteradm/releases/tag/v0.1.0
```
$ clusteradm version
client		version	:v0.1.0
server release	version	:v1.21.1
```

**Comment by pdettori** [comment]
Hi @mikeshng thank you for your prompt response. I am using kind v0.11.1. The new release of clusteradm fixed the issue for me, so I think we can close this issue.
