### ISSUE TITLE
No CSR to approve for managed cluster.

### ISSUE THREAD

**Issue by Dave-Dush** [open-cluster-management-io/clusteradm#120]
Hi,

While I am able to run join command from managed cluster, I get an error when I run `clusteradm accept --clusters cluster1 --context kind-hub `.

The error is **no CSR to approve for cluster cluster1**

However, upon checking `kubectl get managedcluster --context kind-hub` I can see the cluster as accepted but the **availability** tag is _unknown_ and **joined** tag's value is _blank_.

**Comment by mikeshng** [comment]
Hi, which version of clusteradm and `KinD` you are using?

You might have to use the `--force-internal-endpoint-lookup` with the `join` command.

See https://github.com/open-cluster-management-io/clusteradm/issues/109#issuecomment-1020439470 for more details.

**Comment by Dave-Dush** [comment]
I upgraded the kind version to v0.11.1 and now the cluster is joining as normal.

Thanks @mikeshng for helping.
