### ISSUE TITLE
update placement CRD in clusteradm

### ISSUE THREAD

**Issue by jichenjc** [open-cluster-management-io/clusteradm#166]
seeing this error , first line is before download [this yaml file](https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/main/hack/test/placementdecisions.crd.yaml) and apply in the hub cluster ; 2nd line is the output that after the apply above file 

not sure this is covered in other issues already

```
E0321 09:17:26.825849       1 subscription.go:1316] Placement Decision API NOT ready: no matches for kind "PlacementDecision" in version "cluster.open-cluster-management.io/v1beta1"


I0321 09:17:36.851821       1 subscription.go:1330] Placement Decision and Cluster Management Addon APIs are ready

```

**Comment by mgold1234** [comment]
@jichenjc, I  apply this CustomResourceDefinition -➜  kubectl apply -f custom --context=${CTX_HUB_CLUSTER} -n open-cluster-management                                         
customresourcedefinition.apiextensions.k8s.io/placementdecisions.cluster.open-cluster-management.io created
and didn't get this error.
can you please add more details, which version the end-user installed?
it seems that this eror appear with v1beta1.
I looked here-https://github.com/open-cluster-management-io/placement/blob/main/vendor/open-cluster-management.io/api/cluster/v1beta1/types_placementdecision.go and it looks like it added 2 months ago, so maybe you try oldest version?

**Comment by jichenjc** [comment]
um.. I think it's fixed in latest version (0.7?)

at least 0.6 seems have this problem

**Comment by jichenjc** [comment]
I still get this error @mgold1234 ..

the reason my `guess` is the CRD is not created during the cluster init stage 
I am fully follow https://open-cluster-management.io/getting-started/integration/app-lifecycle/
and tried twice got same error 

techinically I guess placement is pre-requirement for this but seems we didn't install it automatically or doc talk about it 


and yes, following works as I did same step, so the question is who should apply this `custom` file and where is it?
< apply this CustomResourceDefinition -➜ kubectl apply -f custom --context=${CTX_HUB_CLUSTER} -n open-cluster-management>

**Comment by jichenjc** [comment]
looks somewhere else ask for 
kubectl apply -f https://raw.githubusercontent.com/open-cluster-management-io/multicloud-operators-subscription/main/deploy/hub-common/apps.open-cluster-management.io_placementrules_crd.yaml

in https://open-cluster-management.io/getting-started/integration/policy-framework/

but didn't see explict ask for placementdecisions ...

**Comment by haoqing0110** [comment]
We had Placement and PlacementDecision API upgrade to v1beta1 version since v0.7.0, refer to the API change log https://github.com/open-cluster-management-io/api/blob/main/CHANGELOG/CHANGELOG-v0.7.md. 

placementrule is another CRD, doesn't require placementdecisions

**Comment by ycyaoxdu** [comment]
> We had Placement and PlacementDecision API upgrade to v1beta1 version since v0.7.0, refer to the API change log https://github.com/open-cluster-management-io/api/blob/main/CHANGELOG/CHANGELOG-v0.7.md.
> 
> placementrule is another CRD, doesn't require placementdecisions

@jichenjc cc

**Comment by jichenjc** [comment]
thanks~!
