### ISSUE TITLE
enhancement: update the output format of `clusterset set `

### ISSUE THREAD

**Issue by jichenjc** [open-cluster-management-io/clusteradm#183]
if the cluster cluster1 not in any clusterset, the output is a little bit confusing

```
# ./clusteradm clusterset set --clusters cluster1 n1
Cluster cluster1 is set, from ClusterSet  to Clusterset n1
```

**Comment by ycyaoxdu** [comment]
Thank you for attentiveness.

And please try to use `--bundle-version=latest` flag while run `clusteradm init` to specify the newest version of registration image. Then you will find out that we've introduced a new concept 'default clusterset' which will automatically include all clusters that in no clusterset. So there will be no cluster not in any clusterset.

Of cource, we may need to do this enhance. thanks for your attentiveness again!

**Comment by jichenjc** [comment]
ok, will close this one and try the method you provided, thanks :)

**Comment by jichenjc** [comment]
@ycyaoxdu I tried the way you provided 

with latest code `c65757fb6f3dba` commit, I compiled clusteradm and 

with this ,it works well
clusteradm init --wait --context ${CTX_HUB_CLUSTER} 

but with following, the clusteradm keep stucking at ` Waiting for cluster manager registration to become ready...` for 5+ min and I Think something wrong there ..

clusteradm init --wait --context ${CTX_HUB_CLUSTER} --bundle-version=latest


will add more logs to see how to provide additional info

**Comment by ycyaoxdu** [comment]
could i get more information about this?

> but with following, the clusteradm keep stucking at ` Waiting for cluster manager registration to become ready...` for 5+ min and I Think something wrong there ..
> 
> clusteradm init --wait --context ${CTX_HUB_CLUSTER} --bundle-version=latest

could i get more information about this? thanks!

**Comment by jichenjc** [comment]
>>>could i get more information about this? thanks!

yes, I am adding more debug logs on this now .. not sure it's my env problem or not

**Comment by jichenjc** [comment]
I tried again and this time it works well , not sure what happened just now ..

so I would say it's a false alarm and sorry about that :(

**Comment by ycyaoxdu** [comment]
Never mind！btw, thanks for your time
