### ISSUE TITLE
move from `create clusterset` to `clusterset create`?

### ISSUE THREAD

**Issue by jichenjc** [open-cluster-management-io/clusteradm#185]
already have 
```
 clusteradm clusterset bind, unbind, set command,

maybe consider move create clusterset to clusterset create instead?
```

**Comment by ycyaoxdu** [comment]
Thanks for your advice!
But, for now, we use `<common-usage>  <resource-type>` to extract and gather the common commands, such as `create`, `get`, `delete`... 
And `<resource-type>  <unique-usage>` for unique commands.

**Comment by jichenjc** [comment]
ok, will keep an eye on this :)

**Comment by ycyaoxdu** [comment]
@jichenjc hi, is there still any problem you're worrying about? if not, maybe you can close this issue:)

**Comment by jichenjc** [comment]
no, this is just a question, not an issue :)
