### ISSUE TITLE
Flakiness observed: test/e2e/clusteradm/joinhubscenario_bootstrsptoken_test.go:39

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/clusteradm#208]
```
CSR clusteradm-e2e-test-c1-47rkl already approved
CSR clusteradm-e2e-test-c1-47rkl already approved
CSR clusteradm-e2e-test-c1-47rkl already approved
CSR clusteradm-e2e-test-c1-47rkl already approved
CSR clusteradm-e2e-test-c1-47rkl already approved
CSR clusteradm-e2e-test-c1-47rkl already approved
CSR clusteradm-e2e-test-c1-47rkl already approved
Error: timed out waiting for the condition

------------------------------
• [FAILED] [526.475 seconds]
test clusteradm with bootstrap token
/home/runner/work/clusteradm/clusteradm/test/e2e/clusteradm/joinhubscenario_bootstrsptoken_test.go:9
  join hub scenario with bootstrap token
  /home/runner/work/clusteradm/clusteradm/test/e2e/clusteradm/joinhubscenario_bootstrsptoken_test.go:19
    [It] should managedclusters join and accepted successfully
    /home/runner/work/clusteradm/clusteradm/test/e2e/clusteradm/joinhubscenario_bootstrsptoken_test.go:23

  Begin Captured GinkgoWriter Output >>
    STEP: init hub with bootstrap token 04/07/22 08:19:21.51
    STEP: managedcluster1 join hub 04/07/22 08:19:21.715
    STEP: reset e2e environment... 04/07/22 08:19:21.819
  << End Captured GinkgoWriter Output

  managedcluster1 join error
  Unexpected error:
      <*exec.ExitError | 0xc00005eb20>: {
          ProcessState: {
              pid: 28092,
              status: 256,
              rusage: {
                  Utime: {Sec: 0, Usec: 47206},
                  Stime: {Sec: 0, Usec: 17165},
                  Maxrss: 52[640](https://github.com/open-cluster-management-io/clusteradm/runs/5864583775?check_suite_focus=true#step:4:640),
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 2527,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 0,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 191,
                  Nivcsw: 112,
              },
          },
          Stderr: nil,
      }
      exit status 1
  occurred
  In [It] at: /home/runner/work/clusteradm/clusteradm/test/e2e/clusteradm/joinhubscenario_bootstrsptoken_test.go:39
------------------------------

Ran 6 of 6 Specs in 1317.903 seconds
FAIL! -- 5 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestE2EClusteradm (1317.90s)
FAIL
FAIL	open-cluster-management.io/clusteradm/test/e2e/clusteradm	1317.910s
FAIL
make: *** [test/e2e/e2e-test.mk:24: test-e2e] Error 1
```

**Comment by ycyaoxdu** [comment]
@yue9944882  hello.
I've tried and found that after execute `clusteradm unjoin` , `clusteradm clean` , but the approved csr still exists. 
following is the output:
```
╭─yuyao@redhats-MacBook-Pro ~/go/bin 
╰─$ clusteradm unjoin --cluster-name cluster1 --context kind-cluster1
Remove applied resources in the managed cluster cluster1 ... 
2022/04/20 10:29:00 Wait to deleted resource klusterlet: klusterlet is still exist
2022/04/20 10:29:01 Wait to deleted resource klusterlet: klusterlet is still exist
2022/04/20 10:29:07 Other resources have been deleted.Applied resources have been deleted during the cluster1 joined stage. 
The status of mcl cluster1 will be unknown in the hub cluster.
╭─yuyao@redhats-MacBook-Pro ~/go/bin 
╰─$ clusteradm clean                                                 
2022/04/20 10:29:13 Wait to delete cluster manager resource: cluster-manager.
2022/04/20 10:29:15 Wait to delete cluster manager resource: cluster-manager.
2022/04/20 10:29:20 Wait to delete cluster manager resource: cluster-manager.
The multicluster hub control plane has been clean up successfully!
╭─yuyao@redhats-MacBook-Pro ~/go/bin 
╰─$ kubectl get pods -A
NAMESPACE            NAME                                        READY   STATUS    RESTARTS   AGE
kube-system          coredns-558bd4d5db-vhqjh                    1/1     Running   0          18m
kube-system          coredns-558bd4d5db-vs56w                    1/1     Running   0          18m
kube-system          etcd-hub-control-plane                      1/1     Running   0          18m
kube-system          kindnet-424xb                               1/1     Running   0          18m
kube-system          kube-apiserver-hub-control-plane            1/1     Running   0          18m
kube-system          kube-controller-manager-hub-control-plane   1/1     Running   0          18m
kube-system          kube-proxy-x4hmk                            1/1     Running   0          18m
kube-system          kube-scheduler-hub-control-plane            1/1     Running   0          18m
local-path-storage   local-path-provisioner-547f784dff-h6rws     1/1     Running   0          18m
╭─yuyao@redhats-MacBook-Pro ~/go/bin 
╰─$ kubectl get csr     
NAME             AGE    SIGNERNAME                                    REQUESTOR                                                         CONDITION
cluster1-kmhtd   104s   kubernetes.io/kube-apiserver-client           system:serviceaccount:open-cluster-management:cluster-bootstrap   Approved,Issued
csr-5rg72        19m    kubernetes.io/kube-apiserver-client-kubelet   system:node:hub-control-plane                                     Approved,Issued
```

---

btw, are you working on this?

**Comment by ycyaoxdu** [comment]
btw, are you working on this?

**Comment by ycyaoxdu** [comment]
> @yue9944882 hello. I've tried and found that after execute `clusteradm unjoin` , `clusteradm clean` , but the approved csr still exists. following is the output:
> 
> ```
> ╭─yuyao@redhats-MacBook-Pro ~/go/bin 
> ╰─$ clusteradm unjoin --cluster-name cluster1 --context kind-cluster1
> Remove applied resources in the managed cluster cluster1 ... 
> 2022/04/20 10:29:00 Wait to deleted resource klusterlet: klusterlet is still exist
> 2022/04/20 10:29:01 Wait to deleted resource klusterlet: klusterlet is still exist
> 2022/04/20 10:29:07 Other resources have been deleted.Applied resources have been deleted during the cluster1 joined stage. 
> The status of mcl cluster1 will be unknown in the hub cluster.
> ╭─yuyao@redhats-MacBook-Pro ~/go/bin 
> ╰─$ clusteradm clean                                                 
> 2022/04/20 10:29:13 Wait to delete cluster manager resource: cluster-manager.
> 2022/04/20 10:29:15 Wait to delete cluster manager resource: cluster-manager.
> 2022/04/20 10:29:20 Wait to delete cluster manager resource: cluster-manager.
> The multicluster hub control plane has been clean up successfully!
> ╭─yuyao@redhats-MacBook-Pro ~/go/bin 
> ╰─$ kubectl get pods -A
> NAMESPACE            NAME                                        READY   STATUS    RESTARTS   AGE
> kube-system          coredns-558bd4d5db-vhqjh                    1/1     Running   0          18m
> kube-system          coredns-558bd4d5db-vs56w                    1/1     Running   0          18m
> kube-system          etcd-hub-control-plane                      1/1     Running   0          18m
> kube-system          kindnet-424xb                               1/1     Running   0          18m
> kube-system          kube-apiserver-hub-control-plane            1/1     Running   0          18m
> kube-system          kube-controller-manager-hub-control-plane   1/1     Running   0          18m
> kube-system          kube-proxy-x4hmk                            1/1     Running   0          18m
> kube-system          kube-scheduler-hub-control-plane            1/1     Running   0          18m
> local-path-storage   local-path-provisioner-547f784dff-h6rws     1/1     Running   0          18m
> ╭─yuyao@redhats-MacBook-Pro ~/go/bin 
> ╰─$ kubectl get csr     
> NAME             AGE    SIGNERNAME                                    REQUESTOR                                                         CONDITION
> cluster1-kmhtd   104s   kubernetes.io/kube-apiserver-client           system:serviceaccount:open-cluster-management:cluster-bootstrap   Approved,Issued
> csr-5rg72        19m    kubernetes.io/kube-apiserver-client-kubelet   system:node:hub-control-plane                                     Approved,Issued
> ```


I'm still working on make sure this is the real reason causing the failure.
If it is, we may claim this issue as a bug? because the approved csr is should be deleted after managedcluster is unjoined.

**Comment by qiujian16** [comment]
/close
this seems fixed already
