### ISSUE TITLE
`init` doesn't work on Kubernetes `v1.24`

### ISSUE THREAD

**Issue by dhaiducek** [open-cluster-management-io/clusteradm#228]
Secrets somehow change on Kubernetes `v1.24`. When I deployed it with Kind `v0.13`, Secrets weren't created when a ServiceAccount was created. For `clusteradm init`, that meant it failed to initialize with this error:
```
Error: secrets "secret with prefix cluster-bootstrap and type kubernetes.io/service-account-token not found in service account open-cluster-management/cluster-bootstrap" not found
```

**Comment by mikeshng** [comment]
As tested by Dale, the workaround for now is to use 
```
clusteradm init --use-bootstrap-token
```
for `KinD` clusters.

I think we might have to update the OCM io website while we investigate what the real issue is.

**Comment by dhaiducek** [comment]
Found it:
>The `LegacyServiceAccountTokenNoAutoGeneration` feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets). (https://github.com/kubernetes/kubernetes/pull/108309, [@zshihang](https://github.com/zshihang))

Reference: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes

**Comment by dhaiducek** [comment]
Duplicate of #252
