### ISSUE TITLE
Failed to install application component with clusteradm client v0.3.0

### ISSUE THREAD

**Issue by yanmxa** [open-cluster-management-io/clusteradm#255]
When I install the application management component in the OCM environment according to the [Application lifecycle management document](https://open-cluster-management.io/getting-started/integration/app-lifecycle/#install-via-clusteradm-cli-tool). I executed the following commands with the latest clusteradm client version - v0.3.0.
```bash
$ kubectl config use-context ${CTX_HUB_CLUSTER}
$ clusteradm install hub-addon --names application-manager
$ kubectl create ns open-cluster-management-agent-addon --context ${CTX_MANAGED_CLUSTER}
$ clusteradm addon enable --name application-manager --cluster ${MANAGED_CLUSTER_NAME}
```
After executing these commands, the application-related CRDs cannot be found on the managed cluster, such as `subscriptions.apps.open-cluster-management.io`  and `subscriptionstatuses.apps.open-cluster-management.io`. But with version v0.2.0, these CRD resources can be created successfully.

**Comment by mikeshng** [comment]
I can't reproduce it on my environment. 
```
$ kubectl --context ${CTX_MANAGED_CLUSTER} get crd | grep sub
subscriptions.apps.open-cluster-management.io          2022-09-15T15:40:38Z
subscriptionstatuses.apps.open-cluster-management.io   2022-09-15T15:40:38Z
```
Could you run and check the following on the hub cluster?
```
kubectl -n open-cluster-management get pod | grep multicluster
```

```
kubectl -n ${MANAGED_CLUSTER_NAME} get managedclusteraddon -o yaml
```
```
kubectl -n ${MANAGED_CLUSTER_NAME} get manifestwork addon-application-manager-deploy -o yaml
```
I am guessing the addon deployment failed.

**Comment by yanmxa** [comment]
Thank you very much, @mikeshng! 

I checked and found that the application-manager addon in my environment did not install successfully.
