### ISSUE TITLE
clusteradm accept command error message is confusing

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/clusteradm#269]
A user ran the clusteradm accept command, and got the following error message:
```
clusteradm accept --clusters cluster1                                                       
CSR cluster1-vv2n5 approved
Error: no CSR to approve for cluster cluster1
```
This error message is confusing because the CSR seems to be approve successfully but then it errors with no CSR to approve.

I did some initial triage and the actual failure might be related to the ManagedCluster CR spec.hubAcceptsClient update failed and when it returned the error up the stack, the error message is incorrectly stated.

The call stack seems to be:
https://github.com/open-cluster-management-io/clusteradm/blob/main/pkg/cmd/accept/exec.go#L77-L79
then
https://github.com/open-cluster-management-io/clusteradm/blob/main/pkg/cmd/accept/exec.go#L186
then it properly failed somewhere in
https://github.com/open-cluster-management-io/clusteradm/blob/main/pkg/cmd/accept/exec.go#L190 
and bubbles back up and prints the confusing error message.

/bug

Reported by @ekarlso in our Slack channel.

**Comment by ekarlso** [comment]
I think this is a false positive, can be closed

**Comment by mikeshng** [comment]
Closing as the original reporter recommended.
