### ISSUE TITLE
Request a guide on how to uninstall OCM

### ISSUE THREAD

**Issue by yanmxa** [open-cluster-management-io/clusteradm#307]
How to use `clusteradm` to initialize a hub control-plane and join a managed cluster into it is covered in the [documentation](https://github.com/open-cluster-management-io/clusteradm/blob/main/README.md). 
But how to use `clusteradm` to uninstall OCM, such as clearing the resources generated by init on hub and clearing the resources generated by joining on a managed cluster. I know that `clusteradm` might support such operations, but to make the most of it, it might be useful to add them to the documentation.

**Comment by mikeshng** [comment]
That's a really good idea, thanks @yanmxa 

Do you want to help contribute this part of the documentation? Either in this repo README or the https://github.com/open-cluster-management-io/open-cluster-management-io.github.io website project.

I think it probably involves `clusteradm unjoin` against all the managed clusters then `clusteradm clean` against the hub cluster.

**Comment by ldpliu** [comment]
/assign @ldpliu 
I will add the hub cluster uninstall steps to readme

**Comment by yanmxa** [comment]
> That's a really good idea, thanks @yanmxa
> 
> Do you want to help contribute this part of the documentation? Either in this repo README or the https://github.com/open-cluster-management-io/open-cluster-management-io.github.io website project.
> 
> I think it probably involves `clusteradm unjoin` against all the managed clusters then `clusteradm clean` against the hub cluster.

Sure!

**Comment by yanmxa** [comment]
Thanks @ldpliu ! I have add the the uninstall command in the readme of this repos.
https://github.com/open-cluster-management-io/clusteradm/pull/310
