### ISSUE TITLE
clusteradm clean didn't remove the boostrap-token in kube-system

### ISSUE THREAD

**Issue by USER0308** [open-cluster-management-io/clusteradm#314]
Env:
    clusteradm v0.9.1

client		version	:v0.4.1
server release	version	:v1.19.0
default bundle	version	:0.9.1

I init with command `clusteradm init **--use-bootstrap-token** --wait`.
Then clusteradm will create a bootstrap-token-{xxxxxx} in `kube-system` namespace, which will not be deleted even if I run `clusteradm clean`.

![image](https://user-images.githubusercontent.com/19644336/219994267-cf3881e4-e249-499a-91a2-879ac196ed3d.png)

I think this is the reason:
The `o.Values.Hub.TokenID` in clean command was inited by random string rather than the token generated in creation.

cmd/clean/exec.go#complete()
```
func (o *Options) complete(cmd *cobra.Command, args []string) (err error) {
	klog.V(1).InfoS("clean options:", "dry-run", o.ClusteradmFlags.DryRun, "output-file", o.OutputFile)
	o.Values = Values{
		Hub: Hub{
			TokenID:     helpers.RandStringRunes_az09(6),
			TokenSecret: helpers.RandStringRunes_az09(16),
		},
	}
	return nil
}
```

cmd/clean/exec.go#Run()
```
func (o *Options) Run() error {
        // ...
    	if err := o.removeBootStrapSecret(kubeClient); err != nil {
		return err
	}
        // ...
}
```

cmd/clean/exec.go#removeBootStrapSecret()
```
func (o *Options) removeBootStrapSecret(client kubernetes.Interface) error {
        // ...
	err = client.CoreV1().
		Secrets("kube-system").
		Delete(context.Background(), "bootstrap-token-"+o.Values.Hub.TokenID, metav1.DeleteOptions{})
	if err != nil && !errors.IsNotFound(err) {
		errs = append(errs, err)
	}
        // ...
}
```

**Comment by mikeshng** [comment]
Thank you for the bug report and triage @USER0308 Please feel free to submit a PR if you are interested and have some free time. Thanks!

**Comment by USER0308** [comment]
It seems that `Hub.TokenID` and `Hub.TokenSecret` are stored in the secret named `bootstrap-token-xxx` only. Once running `clusteradm init --use-bootstrap-token` and `clusteradm clean` repeatly in one k8s cluster,  it will generate several secrets namely like `bootstrap-token-xxx` (just like the picture I post above). And there is no other ways to figure out which secret is in use currently, so that `clusteradm` may not figure out which `bootstrap-token` should be deleted. 

So, how about deleting all of these secrets using `client.CoreV1().Secrets().DeleteCollection()`?  

Code like this:
```
        listOpts := metav1.ListOptions{LabelSelector: "app=cluster-manager"}
	err = client.CoreV1().
		Secrets("kube-system").
		DeleteCollection(context.Background(), metav1.DeleteOptions{}, listOpts)
```

Waiting for your voice! @mikeshng  ^_^

**Comment by mikeshng** [comment]
@USER0308 thank you for the in-depth code analysis. I think what you are suggesting make sense to me.

What do you think @qiujian16 ? I think Xiaojing is looking for some feedback before providing a contribution. Thanks.

**Comment by qiujian16** [comment]
This is a good catch, and I think the fix makes a lot of sense.
