### ISSUE TITLE
clusteradm addon enable does not do any validation or warning about unknown addons

### ISSUE THREAD

**Issue by nirs** [open-cluster-management-io/clusteradm#342]
clusteradm addon manages specific addons, as documented in
https://open-cluster-management.io/getting-started/integration/

but will happily *enable* any name - for example:

```
$ clusteradm addon enable --names foo-bar --clusters dr1,dr2 --context hub
Deploying foo-bar add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr1.
Deploying foo-bar add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr2.
```

On the hub, you see that the new *addon* was added but it remain in `Unknown` state
since there is no such addon.

```
$ kubectl get managedclusteraddons -A --context hub | grep foo-bar
dr1         foo-bar                       Unknown                
dr2         foo-bar                       Unknown                
```

I think the user expectation is:
1. Either don't allow addons that are unknown
2. Or at least warn that this addon is unknown to alert users

See also the discussion in slack:
https://kubernetes.slack.com/archives/C01GE7YSUUF/p1684951933479419

**Comment by mikeshng** [comment]
Maybe we need to check against the `ClusterManagementAddOn` first but I am not sure if `ClusterManagementAddOn` is required.

@ycyaoxdu what do you think?

**Comment by qiujian16** [comment]
ClusterManagementAddOn is actually required
