### ISSUE TITLE
support install template type addon with clusteradm

### ISSUE THREAD

**Issue by zhujian7** [open-cluster-management-io/clusteradm#355]
There is a new way to develop an addon, [using template](https://github.com/open-cluster-management-io/ocm/issues/115), in OCM since v0.12.0. Need to explore how to use the `clusteradm` cli to make developing an addon easier, like:
```
clusteradm addon install hello --type=template --manifests=<manifests-path> ...
```

**Comment by qiujian16** [comment]
this has been done already.
/close
