### ISSUE TITLE
Log will be helpful to contributors.

### ISSUE THREAD

**Issue by dongwangdw** [open-cluster-management-io/clusteradm#36]
I found that there is not any log for this project.
I think this is not really friendly to contributors. When error happens, I really have no idea what was going on.

Even the backtrace will be helpful. But. I only got one line error. That make little scense.

**Comment by itdove** [comment]
I understand, I will check that, the log could be in a default file which can be changed by using a parameter. it will not be in the stdout by default as we don't want to mix the log and the cmd output.

**Comment by dongwangdw** [comment]
@itdove 
I asked this because I had two case yesterday.
When clusteradm did not support oidc, I ran the initial comment agaisg IKS, only one line error throwed out. It took me a while to understand it.

And when I run join command from ocp 4.6.19, it just failed with one line "configmap configmap-ca-crt" not found. And no more. It would be better we can have more info especially for debugging.

I agree with you that this kind of log info should be to cmd output. My opinons are:

1.  switch may be good. User can choose to open the  log or not.
2.  when some action failed, like cmd failed to complete, the error should be prompted to output, possiblly with some backtrace. Currently we already have some error messages, maybe we can improve this.

I will be always here to help.

**Comment by itdove** [comment]
I agree the error is not always clear but all error are bubble up and finally prompted to the output. Do you have an example where it wasn't the case?

**Comment by dongwangdw** [comment]
>When clusteradm did not support oidc, I ran the initial comment agaisg IKS, only one line error throwed out. It took me a while to understand it.

>And when I run join command from ocp 4.6.19, it just failed with one line "configmap configmap-ca-crt" not found. And no more. It would be better we can have more info especially for debugging.

For these two cases, only one line error was prompted without any more info.

**Comment by itdove** [comment]
@dongwangdw If you install the latest by doing https://github.com/open-cluster-management-io/clusteradm/blob/main/README.md#from-source you will be able to use `-v <level>` level being a number to have all logs on the output. 
If you want to have them on a separate file you do either:
```
clusteradm <subcommand> -v 99 2>err.log
```
or
```
clusteradm <subcommand> -v 99 --logtostderr=false --log-file=<your_log_file>
```

I wil add later for logs in the clusteradm itself.

**Comment by dongwangdw** [comment]
Looks like the `v` denotes the log level. It would be better explan some useful level.
I will close this. 
Thanks @itdove

**Comment by itdove** [comment]
I will add this kind of information in the contribute.md https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
