### ISSUE TITLE
join and accept allow duplicate cluster-name

### ISSUE THREAD

**Issue by aii-nozomu-oki** [open-cluster-management-io/clusteradm#361]
If I run `clusteradm join` with the same cluster-name from another cluster, the join succeeds and two CSRs are created in the hub cluster.
In this case, `clusteradm accept` will approve the two CSRs.

Also, if join and approve are done only once and then join and approve are done with the same cluster-name, the join will succeed as well.

The two clusters seem to watch the same namespace in the hub cluster.

Are these expected behaviors?

clusteradm version: v0.6.0

**Comment by qiujian16** [comment]
hrm, I think we should at least print a warning, and let user to choose one csr to approve, instead of directly approve all the csr.

**Comment by aii-nozomu-oki** [comment]
@qiujian16 
Thanks for your efforts.
Incidentally, the same problem exists in the ManagedClusterAutoApproval feature gate.

**Comment by qiujian16** [comment]
yeah we have to resolve it in the controller also cc @skeeey
