### ISSUE TITLE
Can the hub be imported as a managed cluster?

### ISSUE THREAD

**Issue by coleenquadros** [open-cluster-management-io/clusteradm#425]
**Describe the bug**
I am using the following script to import one managed cluster -> https://github.com/open-cluster-management-io/ocm/tree/main/solutions/setup-dev-environment
However I also want to import the hub as a managed cluster too (like self-managed). And I modified the script to make the hub join and try and accept the CSR for it from the hub. However I get the following error about not finding the CSR for hub

**Expected behavior**
I expect the hub to be also imported as a managed cluster

**Comment by coleenquadros** [comment]
`+ echo 'Accept join of hub,cluster1'
Accept join of hub,cluster1
+ KUBECONFIG=/tmp/hub.yaml
+ IS_KIND_ENV=true
+ clusteradm accept --context kind-hub --clusters managed,hub --skip-approve-check
Starting approve csrs for the cluster managed
CSR managed-c592l approved
CSR managed-t9mlg approved
set hubAcceptsClient to true for managed cluster managed

 Your managed cluster managed has joined the Hub successfully. Visit https://open-cluster-management.io/scenarios or https://github.com/open-cluster-management-io/OCM/tree/main/solutions for next steps.
Error: [managedclusters.cluster.open-cluster-management.io "hub" not found, no csr is approved yet for cluster hub]
make: *** [mco-kind-env] Error 1
coquadro@coquadro-mac multicluster-observability-operator % kubeclt get managedclusters -A
zsh: command not found: kubeclt
coquadro@coquadro-mac multicluster-observability-operator % kubectl get managedclusters -A
NAME      HUB ACCEPTED   MANAGED CLUSTER URLS             JOINED   AVAILABLE   AGE
managed   true           https://hub-control-plane:6443   True     True        7m2s
coquadro@coquadro-mac multicluster-observability-operator % `

**Comment by zhujian7** [comment]
Hi @coleenquadros Yes, the hub can be imported as a managed cluster.

Can you paste your commands for init the hub and join the cluster? if you are using a kind cluster, remember to add the `--force-internal-endpoint-lookup` for the `clusteradm join` command. [Here](https://open-cluster-management.io/getting-started/installation/register-a-cluster/#bootstrap-a-klusterlet) is the doc for your reference.

**Comment by coleenquadros** [comment]
HI @zhujian7 

Here is the function 

`
deploy_hub_and_managed_cluster() {
  cd $(dirname ${BASH_SOURCE})

  set -e

  hub=${CLUSTER1:-hub}
  c1=${CLUSTER1:-managed}

  hubctx="kind-${hub}"
  c1ctx="kind-${c1}"

  echo "Initialize the ocm hub cluster\n"
  clusteradm init --wait --context ${hubctx}
  joincmd=$(clusteradm get token --context ${hubctx} | grep clusteradm)

  echo "Join hub to hub\n"
  $(echo ${joincmd} --force-internal-endpoint-lookup --wait --context ${hubctx} | sed "s/<cluster_name>/$c1/g")
  KUBECONFIG=/tmp/managed.yaml IS_KIND_ENV=true
  echo "Join cluster1 to hub\n"
  $(echo ${joincmd} --force-internal-endpoint-lookup --wait --context ${c1ctx} | sed "s/<cluster_name>/$c1/g")

  echo "Accept join of hub,cluster1"
  KUBECONFIG=/tmp/hub.yaml IS_KIND_ENV=true
  clusteradm accept --context ${hubctx} --clusters ${c1},${hub}  --skip-approve-check

  kubectl get managedclusters --all-namespaces --context ${hubctx}
}
`

**Comment by coleenquadros** [comment]
I think I found the issue @zhujian7 
 I duplicated managed clusters command. It worked. 
```
 echo "Join hub to hub\n"
  $(echo ${joincmd} --force-internal-endpoint-lookup --wait --context ${hubctx} | sed "s/<cluster_name>/$c1/g")
```
I will close the issue. Thank you
