### ISSUE TITLE
cluseradm unjoin

### ISSUE THREAD

**Issue by xunpan** [open-cluster-management-io/clusteradm#49]
After a cluster is joined as a managed cluster, it needs an operation to unjoin the managed cluster.
`clusteradm unjoin`

**Comment by dongwangdw** [comment]
I think this sub command make sense.
When a managed cluster want to be detached from hub, some resource should be cleaned manually.
And especially, this cluster may be joined again, the clean env(this managed cluster and hub) will be necessary.

@itdove what do you think?

**Comment by itdove** [comment]
@dongwangdw @xunpan yes it was foreseen implement one.

**Comment by xauthulei** [comment]
There are may be two methods to implement this `unjoin` action:

- `unjoin` from the manged cluster (liking current join process):

1. Log on managed cluster, taking `unjoin action` ,to remove [resources](https://github.com/open-cluster-management-io/clusteradm/tree/main/pkg/cmd/join/scenario/join) in the `join stage`. and send a single to hub.
2. Log on hub cluster,`accept` the single, then remove resources(mcl, resource of managed cluster namespace) if needed.

-  `unjoin` from the hub cluster(liking a delete action): 

1. Log on hub cluster, taking `unjoin action` ,to remove resources in the `accept stage` and pop a message 'execute some cmds on the managed cluster '.
2. Log on managed cluster, execute the cmds to remove the [resources](https://github.com/open-cluster-management-io/clusteradm/tree/main/pkg/cmd/join/scenario/join) in the `join stage`.

The method 2 is easier to achieve than method 1,  Same time, method 1 maybe make sense, but need to consider user 's access right etc , it will be more complex. 

@itdove @dongwangdw and @xunpan , please review this, what is the best option?  or others. Thanks

**Comment by dongwangdw** [comment]
@xauthulei 
From my point, I would prefer to do this from managed cluster, just like the joining process.
So in managed cluster
1. all the resource including the namespaces in managed cluster should be deleted.
2. the managed cluster along with its namespace in hub may be deleted automatically too. 
    This items may needs more work here. I thinks this because when cluster joined, the managed cluster is created in hub from managed cluster. So logically it should be removed from here too. But when I removed all the resources, the manged cluster is not removed automatically. So this may needs some investigations on the registration/Klusterlet.
3. If above two done, now only a CSR left in hub cluster. This one does not affect anythinig. But for the perfect purpose, we may need to clean it too. The ideal way is to remove it from managed cluster too.

So my idea is to unjoin the managed cluster from the managed cluster and clean all the resources created in joining stages.

**Comment by xauthulei** [comment]
> @xauthulei 👍
> 
> this issue may be closed due to the code merged.
@dongwangdw , I will, Thanks
