### ISSUE TITLE
When calling  AddDeployment, the scheme is not set.

### ISSUE THREAD

**Issue by itdove** [open-cluster-management-io/clusteradm#57]
The line at https://github.com/open-cluster-management-io/clusteradm/blob/main/pkg/helpers/apply/apply.go#L48
must be moved to https://github.com/open-cluster-management-io/clusteradm/blob/main/pkg/helpers/apply/apply.go#L71

**Comment by ycyaoxdu** [comment]
@itdove hi, is this issue solved? maybe you can close it. thanks:)

**Comment by ycyaoxdu** [comment]
seems this issue is solved 
/close
