### ISSUE TITLE
Add a --timeout parameter to the join command to let user set the max waiting time on the installation completion of the spoke cluster

### ISSUE THREAD

**Issue by kim-fitness** [open-cluster-management-io/clusteradm#68]
Please consider to add a `--timeout` parameter to the `clusteradm join` command, so that user can set the max waiting time on the installation completion of the spoke cluster.

So far, the `clusteradm join` command waits for at max 300 seconds, which is a hard-coded value.

**Comment by xauthulei** [comment]
I think it is hard for the user to set a suitable value. but if the it reach on the max waiting, we will pop warning message. Thanks

**Comment by ilan-pinto** [comment]
@kim-fitness do you need this flag for setting longer than 300 sec? have you encountered an issue?

**Comment by kim-fitness** [comment]
> 

Hi @ilan-pinto ,
So far, I have not encounter installation issue when doing `clusteradm join`, I'm just assuming someone may have a heavy workload cluster and the `clusteradm join` may takes more than 300 seconds to complete.

**Comment by ilan-pinto** [comment]
i am on it!
