### ISSUE TITLE
clean up the control plane

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/clusteradm#71]
We can now use  clusteradm to destroy  a managed cluster. I will be also helpful to cleanup the hub cluster use cluteradm also.

**Comment by xauthulei** [comment]
@qiujian16 Is seems liking this issue #50 , right ? 

Also, when do the user take this `cleanup` action:

1. After the `clusteradm init` 
2. After the `clusteradm unjoin <managed cluster>`

Please correct me, Thanks

**Comment by qiujian16** [comment]
ah yes, the both are the same. I meant we can clean after clusteradm init

**Comment by xauthulei** [comment]
@qiujian16 ,OK,  I will add a new option(**clean** or **destroy**) for this cleanup action on the Hub. Please let know which one is suitable to us，Thanks

**Comment by qiujian16** [comment]
I think maybe `clean`

**Comment by xauthulei** [comment]
@qiujian16 , you can close this issue, Thanks
