### ISSUE TITLE
add placement image in clustermanager and factoring version/tag flag

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/clusteradm#82]
based on this comment https://github.com/open-cluster-management-io/clusteradm/pull/80#issuecomment-989485226

The placement image's tag could be different from registration/work. We might need to have a release version map to the tags maintained here.

**Comment by ilan-pinto** [comment]
@qiujian16 we have the following images to render 
registration-operator, registration, work

**Comment by qiujian16** [comment]
Thanks!
1. yes.
2. I think so.
