### ISSUE TITLE
`clusteradm accept` does't find the pending CSR for the applying cluster

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/clusteradm#84]
```shell
$ clusteradm accept --clusters cluster1
no CSR to approve for cluster
```
the clusteradm tools cannot find the corresponding CSR resource if the bootstrap token is signed manually instead of reusing 
 the generated tokens from `clusteradm init` commands.
 
 in our case the bootstrap token is copied from the `default` namespace instead of `open-cluster-management` which leads to the clusteradm to ignore the pending CSR from the agent that mounts the manual bootstrap token.
 
https://github.com/open-cluster-management-io/clusteradm/blob/1b0e9b887df77c11a07165f8a05a1079023e902c/pkg/cmd/accept/exec.go#L127-L128

kind of curious why are we filtering the CSRs by the `.spec.groups`?

**Comment by yue9944882** [comment]
cc @qiujian16

**Comment by yue9944882** [comment]
cc @champly

**Comment by qiujian16** [comment]
I think we can add a flag to skip the csr check.

**Comment by mgold1234** [comment]
fixed
/close

**Comment by mgold1234** [comment]
fixed
/close
