### ISSUE TITLE
Release plan?

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/clusteradm#98]
the latest published version is somewhat a `xxx.alpha.yy` version. any plan to cut a non-alpha release for the command line binary?

@qiujian16

**Comment by qiujian16** [comment]
I am fine to cut a non-alpha release in Jan. We did not setup the next release data yet. Maybe we should discuss it on Friday.

**Comment by yue9944882** [comment]
/close

as the release is cut
